SET IDENTITY_INSERT [dbo].[Publisher] ON
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (1, N'Sony')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (2, N'Tencent Holdings Limited')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (3, N'Microsoft')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (4, N'Nintendo')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (5, N'Activision Blizzard')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (6, N'Electronic Arts')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (7, N'Namco')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (8, N'King Digital Entertainment')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (9, N'Ubisoft / Vivendi')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (10, N'GungHo Online Entertainment')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (11, N'CD Projekt')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (12, N'High Moon Studios')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (13, N'BluePoint Games')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (14, N'Double Eleven')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (15, N'ID TECH 7')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (16, N'Square Enix')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (17, N'Toshinobu Matsumiya')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (18, N'Tiny Build Games')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (19, N' Vicarious Visions, Neversoft')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (20, N'Naughty Dog')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (21, N'Shigeru Umebayashi')
INSERT INTO [dbo].[Publishers] ([Id], [PublisherName]) VALUES (22, N' Blizzard Entertainment')
SET IDENTITY_INSERT [dbo].[Publisher] OFF
